export const ProductActionTypes = {
  SET_PRODUCT_CATEGORY: "SET_PRODUCT_CATEGORY",
  SET_PRODUCT_FLAVOUR: "SET_PRODUCT_FLAVOUR",
  SET_PRODUCT_TYPE: "SET_PRODUCT_TYPE",
  SET_PRODUCT_SHAPE: "SET_PRODUCT_SHAPE",
  UPDATE_PRODUCT_SHAPE: "UPDATE_PRODUCT_SHAPE",
};
